sensitiveCodepaths:
  # Files only allowed authors can modify
  # - 'app.js'
  # - 'controllers/**/*.js']
  - '.dryrunsecurity.yaml'
allowedAuthors:
  usernames:
    # GitHub username
    # - 'john-doe'
notificationList:
  # GitHub username or team name
  # - '@DryRunSec/security'
  # - '@john-doe'
  -'@nimbinatus'
